<?php

// Populates a list of Award Types
//
// NOTE: This is a destructive operation.
// It will screw up any associated indices.
// Only run this if you're okay blowing away the entire existing database.

ini_set('display_errors', 'On');

require_once(__DIR__ . "/../config/admin/config.php");
require_once(__DIR__ . "/../config/admin/doctrine.php");
require_once(__DIR__ . "/../db/src/Address.php");
require_once(__DIR__ . "/../db/AddressManager.php");
require_once(__DIR__ . "/../db/src/Region.php");
require_once(__DIR__ . "/../db/RegionManager.php");
require_once(__DIR__ . "/../db/src/Country.php");
require_once(__DIR__ . "/../db/CountryManager.php");
require_once(__DIR__ . "/../vendor/autoload.php");

$us_states = array(
  array("state"=>"Alabama","AL"),
  array("state"=>"Alaska","AK"),
  array("state"=>"Arizona","AZ"),
  array("state"=>"Arkansas","AR"),
  array("state"=>"California","CA"),
  array("state"=>"Colorado","CO"),
  array("state"=>"Connecticut","CT"),
  array("state"=>"Delaware","DE"),
  array("state"=>"District of Columbia","DC"),
  array("state"=>"Florida","FL"),
  array("state"=>"Georgia","GA"),
  array("state"=>"Hawaii","HI"),
  array("state"=>"Idaho","ID"),
  array("state"=>"Illinois","IL"),
  array("state"=>"Indiana","IN"),
  array("state"=>"Iowa","IA"),
  array("state"=>"Kansas","KS"),
  array("state"=>"Kentucky","KY"),
  array("state"=>"Louisiana","LA"),
  array("state"=>"Maine","ME"),
  array("state"=>"Montana","MT"),
  array("state"=>"Nebraska","NE"),
  array("state"=>"Nevada","NV"),
  array("state"=>"New Hampshire","NH"),
  array("state"=>"New Jersey","NJ"),
  array("state"=>"New Mexico","NM"),
  array("state"=>"New York","NY"),
  array("state"=>"North Carolina","NC"),
  array("state"=>"North Dakota","ND"),
  array("state"=>"Ohio","OH"),
  array("state"=>"Oklahoma","OK"),
  array("state"=>"Oregon","OR"),
  array("state"=>"Maryland","MD"),
  array("state"=>"Massachusetts","MA"),
  array("state"=>"Michigan","MI"),
  array("state"=>"Minnesota","MN"),
  array("state"=>"Mississippi","MS"),
  array("state"=>"Missouri","MO"),
  array("state"=>"Pennsylvania","PA"),
  array("state"=>"Rhode Island","RI"),
  array("state"=>"South Carolina","SC"),
  array("state"=>"South Dakota","SD"),
  array("state"=>"Tennessee","TN"),
  array("state"=>"Texas","TX"),
  array("state"=>"Utah","UT"),
  array("state"=>"Vermont","VT"),
  array("state"=>"Virginia","VA"),
  array("state"=>"Washington","WA"),
  array("state"=>"West Virginia","WV"),
  array("state"=>"Wisconsin","WI"),
  array("state"=>"Wyoming","WY")
);


// Random address data generated with https://www.mockaroo.com/
$addresses = array(
  array("description"=>"Dabfeed","address1"=>"5049 Ohio Hill","address2"=>"Training","address3"=>"18-7605664","city"=>"Lille","state"=>"","zip"=>"59044 CEDEX"),
  array("description"=>"Yakidoo","address1"=>"371 Hanover Plaza","address2"=>"Services","address3"=>"","city"=>"Wuyo","state"=>"","zip"=>""),
  array("description"=>"Realbuzz","address1"=>"27 Porter Place","address2"=>"Services","address3"=>"","city"=>"Néa Smýrni","state"=>"","zip"=>""),
  array("description"=>"Photobug","address1"=>"6 Sutteridge Parkway","address2"=>"","address3"=>"","city"=>"Kristiansund N","state"=>"More og Romdal","zip"=>"6517"),
  array("description"=>"Kazio","address1"=>"723 Grasskamp Crossing","address2"=>"Support","address3"=>"55-3903156","city"=>"Maodian","state"=>"","zip"=>""),
  array("description"=>"Topicware","address1"=>"4 Chinook Junction","address2"=>"Product Management","address3"=>"","city"=>"Kratovo","state"=>"","zip"=>"142452"),
  array("description"=>"Kwinu","address1"=>"72 Kensington Lane","address2"=>"Human Resources","address3"=>"","city"=>"Chunshui","state"=>"","zip"=>""),
  array("description"=>"Flipstorm","address1"=>"4 Blaine Place","address2"=>"Sales","address3"=>"","city"=>"Além do Rio","state"=>"","zip"=>"4890-561"),
  array("description"=>"Pixonyx","address1"=>"93431 Sachtjen Point","address2"=>"Human Resources","address3"=>"","city"=>"Jiangkouxu","state"=>"","zip"=>""),
  array("description"=>"Mymm","address1"=>"3047 Gerald Center","address2"=>"Legal","address3"=>"","city"=>"Lianyuan","state"=>"","zip"=>""),
  array("description"=>"Quatz","address1"=>"3529 Kenwood Street","address2"=>"Research and Development","address3"=>"","city"=>"Goworowo","state"=>"","zip"=>"07-440"),
  array("description"=>"Yodo","address1"=>"2 Jackson Place","address2"=>"Engineering","address3"=>"","city"=>"Greenwood","state"=>"Nova Scotia","zip"=>"E6J"),
  array("description"=>"Linklinks","address1"=>"9371 Havey Point","address2"=>"","address3"=>"","city"=>"Karlstad","state"=>"","zip"=>"651 80"),
  array("description"=>"Bluezoom","address1"=>"65464 Blaine Drive","address2"=>"Research and Development","address3"=>"","city"=>"Zhanghua","state"=>"","zip"=>""),
  array("description"=>"Devpoint","address1"=>"5 Pine View Avenue","address2"=>"","address3"=>"","city"=>"Hwasun","state"=>"","zip"=>""),
  array("description"=>"Edgewire","address1"=>"90 Division Crossing","address2"=>"","address3"=>"","city"=>"Vohibinany","state"=>"","zip"=>""),
  array("description"=>"Skynoodle","address1"=>"7 Lotheville Street","address2"=>"","address3"=>"18-9591971","city"=>"Paris 15","state"=>"Île-de-France","zip"=>"75756 CEDEX 15"),
  array("description"=>"Topicshots","address1"=>"8682 American Ash Circle","address2"=>"","address3"=>"","city"=>"Yixin","state"=>"","zip"=>""),
  array("description"=>"Fiveclub","address1"=>"59269 Lakewood Gardens Place","address2"=>"Accounting","address3"=>"","city"=>"Mabai","state"=>"","zip"=>""),
  array("description"=>"Feedfish","address1"=>"4 Lighthouse Bay Point","address2"=>"","address3"=>"","city"=>"Montpellier","state"=>"Languedoc-Roussillon","zip"=>"34080"),
  array("description"=>"Twitterwire","address1"=>"103 Blaine Alley","address2"=>"Services","address3"=>"","city"=>"Zama","state"=>"","zip"=>"228-0027"),
  array("description"=>"Realcube","address1"=>"74 Bunker Hill Road","address2"=>"Sales","address3"=>"","city"=>"Colquechaca","state"=>"","zip"=>""),
  array("description"=>"Photofeed","address1"=>"2056 Fuller Parkway","address2"=>"","address3"=>"","city"=>"Bayside","state"=>"","zip"=>"D13"),
  array("description"=>"Skaboo","address1"=>"40 Cordelia Drive","address2"=>"","address3"=>"87-7570574","city"=>"Wanghu","state"=>"","zip"=>""),
  array("description"=>"Dabshots","address1"=>"6 Becker Hill","address2"=>"","address3"=>"","city"=>"Nong Bua","state"=>"","zip"=>"60110"),
  array("description"=>"Tagpad","address1"=>"2290 Victoria Parkway","address2"=>"","address3"=>"73-6851396","city"=>"Livadiya","state"=>"","zip"=>""),
  array("description"=>"Npath","address1"=>"675 Colorado Road","address2"=>"Accounting","address3"=>"","city"=>"Neiva","state"=>"","zip"=>"410018"),
  array("description"=>"Wordware","address1"=>"89712 Lillian Hill","address2"=>"Research and Development","address3"=>"","city"=>"Heliconia","state"=>"","zip"=>"055827"),
  array("description"=>"Meemm","address1"=>"6785 Fremont Terrace","address2"=>"Engineering","address3"=>"","city"=>"Raychikhinsk","state"=>"","zip"=>"676776"),
  array("description"=>"Shufflebeat","address1"=>"6 Steensland Parkway","address2"=>"Training","address3"=>"","city"=>"Nidek","state"=>"","zip"=>"43-354"),
  array("description"=>"Bubblemix","address1"=>"000 Dovetail Junction","address2"=>"","address3"=>"","city"=>"Zhongzhai","state"=>"","zip"=>""),
  array("description"=>"Trupe","address1"=>"66760 Burning Wood Drive","address2"=>"","address3"=>"","city"=>"Osieczna","state"=>"","zip"=>"83-242"),
  array("description"=>"Plambee","address1"=>"665 Farragut Center","address2"=>"Marketing","address3"=>"","city"=>"Barkā’","state"=>"","zip"=>""),
  array("description"=>"Youspan","address1"=>"5 Bowman Avenue","address2"=>"Marketing","address3"=>"","city"=>"Taozhuang","state"=>"","zip"=>""),
  array("description"=>"Tagtune","address1"=>"50620 Randy Crossing","address2"=>"Services","address3"=>"53-1250594","city"=>"Genet","state"=>"","zip"=>""),
  array("description"=>"Youbridge","address1"=>"5 Union Court","address2"=>"Training","address3"=>"","city"=>"Baochang","state"=>"","zip"=>""),
  array("description"=>"Jetwire","address1"=>"3 Anhalt Junction","address2"=>"Engineering","address3"=>"82-7203321","city"=>"Juliaca","state"=>"","zip"=>""),
  array("description"=>"Trilith","address1"=>"8 Namekagon Pass","address2"=>"Sales","address3"=>"","city"=>"Pardubice","state"=>"","zip"=>"530 12"),
  array("description"=>"Shufflebeat","address1"=>"1381 North Point","address2"=>"Engineering","address3"=>"","city"=>"Messina","state"=>"Sicilia","zip"=>"98124"),
  array("description"=>"Oyoyo","address1"=>"6490 Rigney Circle","address2"=>"Research and Development","address3"=>"","city"=>"Shaxi","state"=>"","zip"=>""),
  array("description"=>"Jetpulse","address1"=>"3093 Barnett Pass","address2"=>"Accounting","address3"=>"","city"=>"Badar","state"=>"","zip"=>"665212"),
  array("description"=>"Innojam","address1"=>"65 Rusk Hill","address2"=>"","address3"=>"","city"=>"Tangquan","state"=>"","zip"=>""),
  array("description"=>"Gabtune","address1"=>"779 Banding Court","address2"=>"Support","address3"=>"","city"=>"Tikhvin","state"=>"","zip"=>"187557"),
  array("description"=>"Janyx","address1"=>"33 Blaine Lane","address2"=>"Product Management","address3"=>"","city"=>"Qo‘qon","state"=>"","zip"=>""),
  array("description"=>"Centidel","address1"=>"7 Lunder Plaza","address2"=>"","address3"=>"","city"=>"Žrnovo","state"=>"","zip"=>"20275"),
  array("description"=>"Thoughtbeat","address1"=>"5 Petterle Court","address2"=>"Training","address3"=>"","city"=>"Skhodnya","state"=>"","zip"=>"143020"),
  array("description"=>"Wordify","address1"=>"9810 Lawn Street","address2"=>"","address3"=>"","city"=>"Balabag","state"=>"","zip"=>"5001"),
  array("description"=>"Gabspot","address1"=>"73733 Merry Crossing","address2"=>"Accounting","address3"=>"","city"=>"Malko Tŭrnovo","state"=>"","zip"=>"8359"),
  array("description"=>"Buzzdog","address1"=>"8892 Pearson Crossing","address2"=>"Legal","address3"=>"51-1620204","city"=>"Lanús","state"=>"","zip"=>"1870"),
  array("description"=>"Gabspot","address1"=>"651 Blaine Terrace","address2"=>"Product Management","address3"=>"","city"=>"Åmål","state"=>"Västra Götaland","zip"=>"662 33"),
  array("description"=>"Bubbletube","address1"=>"8 Banding Way","address2"=>"Accounting","address3"=>"","city"=>"København","state"=>"Region Hovedstaden","zip"=>"1068"),
  array("description"=>"Skimia","address1"=>"37374 Valley Edge Terrace","address2"=>"Business Development","address3"=>"","city"=>"Besah","state"=>"","zip"=>""),
  array("description"=>"Yombu","address1"=>"5 Northfield Junction","address2"=>"Legal","address3"=>"","city"=>"Lons-le-Saunier","state"=>"Franche-Comté","zip"=>"39039 CEDEX 9"),
  array("description"=>"Skinder","address1"=>"97362 Comanche Court","address2"=>"","address3"=>"","city"=>"Huaqiao","state"=>"","zip"=>""),
  array("description"=>"Quire","address1"=>"916 Lakewood Point","address2"=>"Support","address3"=>"","city"=>"Sawahrandu","state"=>"","zip"=>""),
  array("description"=>"Meedoo","address1"=>"19 Bowman Center","address2"=>"Business Development","address3"=>"10-6020748","city"=>"Carreira","state"=>"Braga","zip"=>"4820-021"),
  array("description"=>"Nlounge","address1"=>"22927 Stephen Center","address2"=>"Support","address3"=>"23-7028600","city"=>"Hino","state"=>"","zip"=>"919-0222"),
  array("description"=>"Flipopia","address1"=>"57594 Melrose Pass","address2"=>"","address3"=>"","city"=>"Natu","state"=>"","zip"=>""),
  array("description"=>"Abata","address1"=>"0888 Blaine Trail","address2"=>"Business Development","address3"=>"","city"=>"Bergen","state"=>"Hordaland","zip"=>"5849"),
  array("description"=>"Skinte","address1"=>"36 Norway Maple Avenue","address2"=>"","address3"=>"","city"=>"Gaspar","state"=>"","zip"=>"89110-000"),
  array("description"=>"Lazzy","address1"=>"524 Lotheville Trail","address2"=>"Legal","address3"=>"","city"=>"Krzyżowice","state"=>"","zip"=>"43-254"),
  array("description"=>"Flipbug","address1"=>"688 Scoville Plaza","address2"=>"Sales","address3"=>"","city"=>"Gornyy","state"=>"","zip"=>"413545"),
  array("description"=>"Mynte","address1"=>"5472 Old Gate Alley","address2"=>"Accounting","address3"=>"","city"=>"Ilanskiy","state"=>"","zip"=>"663800"),
  array("description"=>"Quimm","address1"=>"87717 Badeau Road","address2"=>"","address3"=>"","city"=>"Suisan","state"=>"","zip"=>""),
  array("description"=>"Tekfly","address1"=>"98 Dapin Street","address2"=>"","address3"=>"","city"=>"Dąbrowice","state"=>"","zip"=>"99-352"),
  array("description"=>"Eazzy","address1"=>"9 Sunfield Pass","address2"=>"Legal","address3"=>"01-7167381","city"=>"Lukrejo","state"=>"","zip"=>""),
  array("description"=>"Buzzdog","address1"=>"29362 Stephen Plaza","address2"=>"Sales","address3"=>"","city"=>"Qiancang","state"=>"","zip"=>""),
  array("description"=>"BlogXS","address1"=>"76 Susan Point","address2"=>"Accounting","address3"=>"","city"=>"Talu","state"=>"","zip"=>""),
  array("description"=>"Kanoodle","address1"=>"9 Lukken Pass","address2"=>"Marketing","address3"=>"","city"=>"Dulangan","state"=>"","zip"=>"5203"),
  array("description"=>"Aimbu","address1"=>"51732 Luster Avenue","address2"=>"Marketing","address3"=>"","city"=>"Yuncheng","state"=>"","zip"=>""),
  array("description"=>"Edgeblab","address1"=>"48353 Leroy Terrace","address2"=>"Human Resources","address3"=>"16-2856375","city"=>"Ribeirão Pires","state"=>"","zip"=>"09400-000"),
  array("description"=>"Fivechat","address1"=>"05601 Straubel Center","address2"=>"Business Development","address3"=>"","city"=>"Meixi","state"=>"","zip"=>""),
  array("description"=>"Yacero","address1"=>"1575 Reindahl Road","address2"=>"","address3"=>"","city"=>"Vanves","state"=>"Île-de-France","zip"=>"92179 CEDEX"),
  array("description"=>"Devcast","address1"=>"89 Drewry Road","address2"=>"","address3"=>"","city"=>"Gubskaya","state"=>"","zip"=>"352552"),
  array("description"=>"Mudo","address1"=>"97 Lerdahl Drive","address2"=>"Support","address3"=>"","city"=>"Qorovulbozor","state"=>"","zip"=>""),
  array("description"=>"Layo","address1"=>"5715 Stuart Alley","address2"=>"Product Management","address3"=>"","city"=>"Kortowo","state"=>"","zip"=>"11-041"),
  array("description"=>"Tagopia","address1"=>"5062 Ronald Regan Place","address2"=>"Business Development","address3"=>"","city"=>"Sanxiang","state"=>"","zip"=>""),
  array("description"=>"Zoozzy","address1"=>"39025 Pawling Court","address2"=>"Business Development","address3"=>"","city"=>"Kotlovka","state"=>"","zip"=>"142817"),
  array("description"=>"Jabberbean","address1"=>"85 Montana Court","address2"=>"Business Development","address3"=>"","city"=>"Kolambugan","state"=>"","zip"=>"2100"),
  array("description"=>"Jabbercube","address1"=>"38 Mallard Plaza","address2"=>"Engineering","address3"=>"10-7706085","city"=>"Kambia","state"=>"","zip"=>""),
  array("description"=>"Mybuzz","address1"=>"9892 Ohio Plaza","address2"=>"Training","address3"=>"","city"=>"Nanga Eboko","state"=>"","zip"=>""),
  array("description"=>"Snaptags","address1"=>"3011 Shoshone Alley","address2"=>"Training","address3"=>"","city"=>"Mali","state"=>"","zip"=>""),
  array("description"=>"Rhycero","address1"=>"8 Westerfield Park","address2"=>"Legal","address3"=>"","city"=>"Viana","state"=>"","zip"=>"65215-000"),
  array("description"=>"Dabtype","address1"=>"1322 Dayton Center","address2"=>"","address3"=>"","city"=>"Pitanga","state"=>"","zip"=>"85200-000"),
  array("description"=>"Meevee","address1"=>"58 Ronald Regan Lane","address2"=>"Training","address3"=>"","city"=>"Sena","state"=>"","zip"=>"13110"),
  array("description"=>"Buzzster","address1"=>"09 Cherokee Point","address2"=>"","address3"=>"","city"=>"Pio Duran","state"=>"","zip"=>"5046"),
  array("description"=>"Youfeed","address1"=>"0869 School Pass","address2"=>"Engineering","address3"=>"","city"=>"Philadelphia","state"=>"","zip"=>"19146"),
  array("description"=>"Eire","address1"=>"7 Hayes Crossing","address2"=>"Product Management","address3"=>"","city"=>"Cidamar","state"=>"","zip"=>""),
  array("description"=>"Twimm","address1"=>"3607 John Wall Drive","address2"=>"Engineering","address3"=>"11-3767269","city"=>"Surkhet","state"=>"","zip"=>""),
  array("description"=>"Abatz","address1"=>"958 Hovde Pass","address2"=>"Support","address3"=>"","city"=>"Uychi","state"=>"","zip"=>""),
  array("description"=>"Kimia","address1"=>"94211 New Castle Alley","address2"=>"Business Development","address3"=>"10-6275822","city"=>"Dongxing","state"=>"","zip"=>""),
  array("description"=>"Realmix","address1"=>"95120 Park Meadow Center","address2"=>"Services","address3"=>"","city"=>"Lazarevskoye","state"=>"","zip"=>"397474"),
  array("description"=>"Jaxnation","address1"=>"10107 Fieldstone Terrace","address2"=>"Accounting","address3"=>"","city"=>"Trenton","state"=>"New Jersey","zip"=>"08695"),
  array("description"=>"Lazz","address1"=>"0 Schlimgen Terrace","address2"=>"","address3"=>"","city"=>"Mae Fa Luang","state"=>"","zip"=>"25190"),
  array("description"=>"Nlounge","address1"=>"00 Rusk Place","address2"=>"","address3"=>"","city"=>"Port Saint John’s","state"=>"","zip"=>"6625"),
  array("description"=>"Dynazzy","address1"=>"4 Schlimgen Hill","address2"=>"Sales","address3"=>"","city"=>"Tancheng","state"=>"","zip"=>""),
  array("description"=>"Zava","address1"=>"21151 Reinke Place","address2"=>"","address3"=>"","city"=>"Samashki","state"=>"","zip"=>"366602"),
  array("description"=>"Leexo","address1"=>"92593 Main Drive","address2"=>"Training","address3"=>"","city"=>"Luodian","state"=>"","zip"=>""),
  array("description"=>"Yamia","address1"=>"97 Kim Plaza","address2"=>"Business Development","address3"=>"","city"=>"Dupnitsa","state"=>"","zip"=>""),
  array("description"=>"Riffpath","address1"=>"7 Columbus Point","address2"=>"","address3"=>"","city"=>"Fengcheng","state"=>"","zip"=>""),
  array("description"=>"Flipopia","address1"=>"81 Pleasure Park","address2"=>"Support","address3"=>"","city"=>"Banjar Dauhmargi","state"=>"","zip"=>""),
  array("description"=>"Quamba","address1"=>"1 Brentwood Lane","address2"=>"Human Resources","address3"=>"","city"=>"Ares Tengah","state"=>"","zip"=>""),
  array("description"=>"Kare","address1"=>"5138 Raven Park","address2"=>"Human Resources","address3"=>"","city"=>"Capacmarca","state"=>"","zip"=>""),
  array("description"=>"Plajo","address1"=>"58 Garrison Alley","address2"=>"Sales","address3"=>"","city"=>"Shanghuang","state"=>"","zip"=>""),
  array("description"=>"Eidel","address1"=>"090 Roth Trail","address2"=>"Research and Development","address3"=>"58-5081330","city"=>"Ordos","state"=>"","zip"=>""),
  array("description"=>"Skaboo","address1"=>"1 Fair Oaks Trail","address2"=>"Engineering","address3"=>"","city"=>"Bang Mun Nak","state"=>"","zip"=>"66120"),
  array("description"=>"Katz","address1"=>"1773 Corscot Place","address2"=>"Marketing","address3"=>"","city"=>"Xintai","state"=>"","zip"=>""),
  array("description"=>"Thoughtstorm","address1"=>"4821 Esker Circle","address2"=>"Sales","address3"=>"","city"=>"Baishigou","state"=>"","zip"=>""),
  array("description"=>"Buzzbean","address1"=>"06230 Towne Alley","address2"=>"Legal","address3"=>"42-3652794","city"=>"Diré","state"=>"","zip"=>""),
  array("description"=>"Photolist","address1"=>"355 Continental Lane","address2"=>"Product Management","address3"=>"69-5345633","city"=>"Funehikimachi-funehiki","state"=>"","zip"=>"963-4603"),
  array("description"=>"Jabberbean","address1"=>"919 Pepper Wood Avenue","address2"=>"","address3"=>"","city"=>"Žemaičių Naumiestis","state"=>"","zip"=>"99005"),
  array("description"=>"LiveZ","address1"=>"1029 Shoshone Plaza","address2"=>"","address3"=>"65-6999134","city"=>"Kimovsk","state"=>"","zip"=>"301723"),
  array("description"=>"Mydo","address1"=>"31 Bunker Hill Road","address2"=>"Support","address3"=>"46-2436828","city"=>"Oslo","state"=>"Oslo","zip"=>"0315"),
  array("description"=>"Voolia","address1"=>"0460 Scoville Court","address2"=>"","address3"=>"","city"=>"Šipovo","state"=>"","zip"=>""),
  array("description"=>"Livetube","address1"=>"447 Morrow Circle","address2"=>"","address3"=>"","city"=>"Qumudi","state"=>"","zip"=>""),
  array("description"=>"Voonyx","address1"=>"40 Oxford Trail","address2"=>"Sales","address3"=>"","city"=>"Kuching","state"=>"","zip"=>"93916"),
  array("description"=>"Devbug","address1"=>"6101 Lake View Pass","address2"=>"","address3"=>"","city"=>"Bundoc","state"=>"","zip"=>"3515"),
  array("description"=>"Tagfeed","address1"=>"50339 Dunning Plaza","address2"=>"Research and Development","address3"=>"","city"=>"Huancapi","state"=>"","zip"=>""),
  array("description"=>"Bubblebox","address1"=>"5149 Mayer Terrace","address2"=>"Business Development","address3"=>"","city"=>"Sidenreng","state"=>"","zip"=>""),
  array("description"=>"Eimbee","address1"=>"64282 Thompson Street","address2"=>"Research and Development","address3"=>"","city"=>"Quinta da Torre","state"=>"Viana do Castelo","zip"=>"4920-070"),
  array("description"=>"Skalith","address1"=>"9315 Wayridge Place","address2"=>"Human Resources","address3"=>"","city"=>"København","state"=>"Region Hovedstaden","zip"=>"1738"),
  array("description"=>"Dynava","address1"=>"203 Carpenter Crossing","address2"=>"Product Management","address3"=>"","city"=>"Kap Choeng","state"=>"","zip"=>"57210"),
  array("description"=>"Zava","address1"=>"6326 Luster Court","address2"=>"","address3"=>"","city"=>"Huacaschuque","state"=>"","zip"=>""),
  array("description"=>"Demizz","address1"=>"24778 4th Alley","address2"=>"Engineering","address3"=>"","city"=>"Vsetín","state"=>"","zip"=>"755 01"),
  array("description"=>"Trilia","address1"=>"5740 Lunder Crossing","address2"=>"Accounting","address3"=>"","city"=>"Pécs","state"=>"Baranya","zip"=>"7631"),
  array("description"=>"Vitz","address1"=>"555 Hoffman Parkway","address2"=>"Engineering","address3"=>"","city"=>"Roshal’","state"=>"","zip"=>"140732"),
  array("description"=>"Tagchat","address1"=>"3287 Fair Oaks Park","address2"=>"","address3"=>"","city"=>"Futaleufú","state"=>"","zip"=>""),
  array("description"=>"Quimm","address1"=>"2351 Buell Park","address2"=>"Legal","address3"=>"20-0719806","city"=>"Dadiharja","state"=>"","zip"=>""),
  array("description"=>"Reallinks","address1"=>"6834 Birchwood Alley","address2"=>"Product Management","address3"=>"","city"=>"Guadalupe","state"=>"Mexico","zip"=>"52107"),
  array("description"=>"Zoonder","address1"=>"36671 Granby Plaza","address2"=>"","address3"=>"","city"=>"Łapczyca","state"=>"","zip"=>"32-744"),
  array("description"=>"Browsedrive","address1"=>"6 Declaration Court","address2"=>"","address3"=>"","city"=>"Narathiwat","state"=>"","zip"=>"90220"),
  array("description"=>"Topdrive","address1"=>"0354 Pine View Drive","address2"=>"","address3"=>"","city"=>"Encrucijada","state"=>"","zip"=>""),
  array("description"=>"Bubblemix","address1"=>"143 Shasta Park","address2"=>"Support","address3"=>"","city"=>"Wólka Pełkińska","state"=>"","zip"=>"37-511"),
  array("description"=>"Ozu","address1"=>"9 Debs Trail","address2"=>"Business Development","address3"=>"","city"=>"Puente Alto","state"=>"","zip"=>""),
  array("description"=>"Dabshots","address1"=>"036 Rigney Lane","address2"=>"Business Development","address3"=>"","city"=>"Freire","state"=>"","zip"=>""),
  array("description"=>"Zoovu","address1"=>"55402 Boyd Parkway","address2"=>"Business Development","address3"=>"","city"=>"Cikijing","state"=>"","zip"=>""),
  array("description"=>"Abatz","address1"=>"1 John Wall Avenue","address2"=>"Engineering","address3"=>"","city"=>"Gudurica","state"=>"","zip"=>""),
  array("description"=>"Kwinu","address1"=>"6102 Sauthoff Drive","address2"=>"Marketing","address3"=>"","city"=>"Luts’k","state"=>"","zip"=>""),
  array("description"=>"Mycat","address1"=>"733 Sauthoff Road","address2"=>"","address3"=>"","city"=>"Majayjay","state"=>"","zip"=>"4005"),
  array("description"=>"Kazio","address1"=>"2970 Loeprich Crossing","address2"=>"","address3"=>"","city"=>"Neyvo-Rudyanka","state"=>"","zip"=>"624170"),
  array("description"=>"Tanoodle","address1"=>"3 Merrick Street","address2"=>"Product Management","address3"=>"","city"=>"Kos","state"=>"","zip"=>""),
  array("description"=>"Oyondu","address1"=>"0 Derek Pass","address2"=>"Support","address3"=>"","city"=>"Shangganshan","state"=>"","zip"=>""),
  array("description"=>"Kwinu","address1"=>"4153 Atwood Street","address2"=>"","address3"=>"","city"=>"Santana do Ipanema","state"=>"","zip"=>""),
  array("description"=>"Divavu","address1"=>"30546 Prairie Rose Pass","address2"=>"","address3"=>"","city"=>"Sarandi","state"=>"","zip"=>"99560-000"),
  array("description"=>"Thoughtbridge","address1"=>"5 Arkansas Park","address2"=>"Human Resources","address3"=>"","city"=>"Taibao","state"=>"","zip"=>""),
  array("description"=>"Meevee","address1"=>"6215 Acker Alley","address2"=>"Research and Development","address3"=>"","city"=>"Bendan","state"=>"","zip"=>""),
  array("description"=>"Mynte","address1"=>"55 Kingsford Street","address2"=>"Services","address3"=>"","city"=>"Al Maşdūr","state"=>"","zip"=>""),
  array("description"=>"Youfeed","address1"=>"7106 Coolidge Avenue","address2"=>"","address3"=>"","city"=>"Belozërskoye","state"=>"","zip"=>"641360"),
  array("description"=>"Oozz","address1"=>"455 Mayer Street","address2"=>"Human Resources","address3"=>"","city"=>"Ōnojō","state"=>"","zip"=>"818-0138"),
  array("description"=>"Npath","address1"=>"5518 Vidon Place","address2"=>"Research and Development","address3"=>"","city"=>"Praia da Tocha","state"=>"Coimbra","zip"=>"3060-681"),
  array("description"=>"Meezzy","address1"=>"9 Blackbird Junction","address2"=>"","address3"=>"","city"=>"Camilo Aldao","state"=>"","zip"=>"5285"),
  array("description"=>"Thoughtbridge","address1"=>"7865 Cardinal Road","address2"=>"Training","address3"=>"81-7370520","city"=>"Ligang","state"=>"","zip"=>""),
  array("description"=>"Realbuzz","address1"=>"960 Farmco Pass","address2"=>"","address3"=>"","city"=>"Balad","state"=>"","zip"=>""),
  array("description"=>"Skyble","address1"=>"884 Gale Point","address2"=>"Support","address3"=>"","city"=>"San Pedro","state"=>"","zip"=>"4500"),
  array("description"=>"Midel","address1"=>"708 Dennis Terrace","address2"=>"Support","address3"=>"","city"=>"Aix-en-Provence","state"=>"Provence-Alpes-Côte d'Azur","zip"=>"13540"),
  array("description"=>"Vimbo","address1"=>"37538 Gerald Place","address2"=>"Support","address3"=>"","city"=>"Roubaix","state"=>"Nord-Pas-de-Calais","zip"=>"59073 CEDEX 1"),
  array("description"=>"Katz","address1"=>"00 Park Meadow Trail","address2"=>"Engineering","address3"=>"","city"=>"Ejido","state"=>"","zip"=>""),
  array("description"=>"Katz","address1"=>"034 Lawn Parkway","address2"=>"Accounting","address3"=>"","city"=>"San Agustin","state"=>"Guanajuato","zip"=>"36800"),
  array("description"=>"Divanoodle","address1"=>"746 Hayes Drive","address2"=>"Sales","address3"=>"48-0233995","city"=>"Hønefoss","state"=>"Buskerud","zip"=>"3519"),
  array("description"=>"Photobug","address1"=>"27761 Donald Place","address2"=>"Accounting","address3"=>"","city"=>"Thap Khlo","state"=>"","zip"=>"71000"),
  array("description"=>"Wordpedia","address1"=>"47 Carioca Street","address2"=>"","address3"=>"","city"=>"Santo Domingo","state"=>"","zip"=>"4508"),
  array("description"=>"Wikibox","address1"=>"6218 Jenifer Plaza","address2"=>"Human Resources","address3"=>"","city"=>"Xinqiao","state"=>"","zip"=>""),
  array("description"=>"Riffpedia","address1"=>"29482 Bonner Trail","address2"=>"Legal","address3"=>"","city"=>"Cisownica","state"=>"","zip"=>"43-450"),
  array("description"=>"Omba","address1"=>"976 Holmberg Junction","address2"=>"Business Development","address3"=>"","city"=>"Vellinge","state"=>"Skåne","zip"=>"235 36"),
  array("description"=>"Yakidoo","address1"=>"777 Crownhardt Plaza","address2"=>"Marketing","address3"=>"","city"=>"Nueva Vida Sur","state"=>"","zip"=>"6224"),
  array("description"=>"JumpXS","address1"=>"0 Weeping Birch Circle","address2"=>"Research and Development","address3"=>"","city"=>"Trenton","state"=>"New Jersey","zip"=>"08650"),
  array("description"=>"Devpulse","address1"=>"10122 Russell Way","address2"=>"Accounting","address3"=>"","city"=>"Donglu","state"=>"","zip"=>""),
  array("description"=>"Youopia","address1"=>"8 Nelson Terrace","address2"=>"Marketing","address3"=>"14-2818498","city"=>"Tayu","state"=>"","zip"=>""),
  array("description"=>"Twitterlist","address1"=>"90367 Birchwood Place","address2"=>"Research and Development","address3"=>"61-4389741","city"=>"Toledo","state"=>"Castilla - La Mancha","zip"=>"45071"),
  array("description"=>"Eidel","address1"=>"47 Portage Road","address2"=>"Accounting","address3"=>"","city"=>"Khorinsk","state"=>"","zip"=>"671410"),
  array("description"=>"Skyndu","address1"=>"57268 Truax Court","address2"=>"Marketing","address3"=>"","city"=>"Bibiani","state"=>"","zip"=>""),
  array("description"=>"Fanoodle","address1"=>"2 Westerfield Parkway","address2"=>"","address3"=>"42-9685319","city"=>"Boshan","state"=>"","zip"=>""),
  array("description"=>"Mynte","address1"=>"494 Ilene Hill","address2"=>"Services","address3"=>"","city"=>"Majayjay","state"=>"","zip"=>"4005"),
  array("description"=>"Voonder","address1"=>"752 Forest Run Way","address2"=>"","address3"=>"","city"=>"Nāḩiyat as Sab‘ Biyār","state"=>"","zip"=>""),
  array("description"=>"Avamba","address1"=>"1038 Carey Junction","address2"=>"Engineering","address3"=>"","city"=>"Lagoa do Itaenga","state"=>"","zip"=>"55840-000"),
  array("description"=>"Avamba","address1"=>"23 Granby Center","address2"=>"Research and Development","address3"=>"","city"=>"Akoupé","state"=>"","zip"=>""),
  array("description"=>"Brainverse","address1"=>"78 Charing Cross Lane","address2"=>"","address3"=>"","city"=>"Jiuli","state"=>"","zip"=>""),
  array("description"=>"Eadel","address1"=>"7098 Eastwood Trail","address2"=>"","address3"=>"14-1191286","city"=>"Guaratinguetá","state"=>"","zip"=>"12500-000"),
  array("description"=>"Quinu","address1"=>"7 Bultman Avenue","address2"=>"","address3"=>"","city"=>"Kacha","state"=>"","zip"=>""),
  array("description"=>"Devbug","address1"=>"2612 Kedzie Parkway","address2"=>"","address3"=>"","city"=>"Lamu","state"=>"","zip"=>""),
  array("description"=>"Roodel","address1"=>"2469 Stephen Center","address2"=>"Support","address3"=>"","city"=>"Ar Rifā‘","state"=>"","zip"=>""),
  array("description"=>"Browsezoom","address1"=>"91 La Follette Alley","address2"=>"Marketing","address3"=>"","city"=>"Chengyue","state"=>"","zip"=>""),
  array("description"=>"Voonte","address1"=>"0 Blaine Park","address2"=>"Sales","address3"=>"","city"=>"Domaniewice","state"=>"","zip"=>"99-434"),
  array("description"=>"Zoonoodle","address1"=>"4 Mallard Park","address2"=>"Accounting","address3"=>"","city"=>"Vyborg","state"=>"","zip"=>"188919"),
  array("description"=>"Gabcube","address1"=>"945 Maryland Park","address2"=>"Legal","address3"=>"","city"=>"Palmira","state"=>"","zip"=>"763547"),
  array("description"=>"Youfeed","address1"=>"7 Knutson Road","address2"=>"Research and Development","address3"=>"","city"=>"Puncakmanis","state"=>"","zip"=>""),
  array("description"=>"Skyba","address1"=>"94916 Walton Street","address2"=>"Services","address3"=>"","city"=>"Balite","state"=>"","zip"=>"2302"),
  array("description"=>"Shufflester","address1"=>"0728 Blaine Circle","address2"=>"","address3"=>"","city"=>"Kainan","state"=>"","zip"=>"649-6326"),
  array("description"=>"Dazzlesphere","address1"=>"05947 Ridge Oak Park","address2"=>"","address3"=>"45-8556913","city"=>"Lavradio","state"=>"Setúbal","zip"=>"2835-305"),
  array("description"=>"Divanoodle","address1"=>"0599 Havey Park","address2"=>"Product Management","address3"=>"","city"=>"Shumikha","state"=>"","zip"=>"641115"),
  array("description"=>"Kare","address1"=>"154 Southridge Park","address2"=>"Sales","address3"=>"63-1347735","city"=>"Banī Zayd","state"=>"","zip"=>""),
  array("description"=>"Kwilith","address1"=>"00903 Delaware Trail","address2"=>"Marketing","address3"=>"","city"=>"Tanahwulan","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"80 Hauk Place","address2"=>"","address3"=>"","city"=>"Bobigny","state"=>"Île-de-France","zip"=>"93017 CEDEX"),
  array("description"=>"Feedfire","address1"=>"4601 Everett Center","address2"=>"Sales","address3"=>"","city"=>"Vasyl'evsky Ostrov","state"=>"","zip"=>"190990"),
  array("description"=>"Wordpedia","address1"=>"50 Sunbrook Parkway","address2"=>"Legal","address3"=>"","city"=>"North York","state"=>"Ontario","zip"=>"M3H"),
  array("description"=>"Mynte","address1"=>"70 Reindahl Pass","address2"=>"Sales","address3"=>"89-3032227","city"=>"Bateria","state"=>"","zip"=>"6012"),
  array("description"=>"Tekfly","address1"=>"2220 Myrtle Pass","address2"=>"Research and Development","address3"=>"","city"=>"Tanahwangko","state"=>"","zip"=>""),
  array("description"=>"Babbleblab","address1"=>"0 Hudson Parkway","address2"=>"Legal","address3"=>"","city"=>"Berlín","state"=>"","zip"=>""),
  array("description"=>"Kazio","address1"=>"0 Randy Center","address2"=>"Legal","address3"=>"","city"=>"Huifeng","state"=>"","zip"=>""),
  array("description"=>"Brainsphere","address1"=>"27 Anhalt Junction","address2"=>"Marketing","address3"=>"","city"=>"Oslo","state"=>"Oslo","zip"=>"0188"),
  array("description"=>"Shuffletag","address1"=>"1 Brown Road","address2"=>"Product Management","address3"=>"","city"=>"Madīnat Ḩamad","state"=>"","zip"=>""),
  array("description"=>"Kwideo","address1"=>"3803 Rieder Plaza","address2"=>"Engineering","address3"=>"","city"=>"Mangaran","state"=>"","zip"=>""),
  array("description"=>"Vinte","address1"=>"55857 Oak Point","address2"=>"","address3"=>"","city"=>"La Guata","state"=>"","zip"=>""),
  array("description"=>"Abata","address1"=>"77 Lukken Terrace","address2"=>"Business Development","address3"=>"","city"=>"Porosozero","state"=>"","zip"=>"186855"),
  array("description"=>"Innotype","address1"=>"6811 Nevada Parkway","address2"=>"Human Resources","address3"=>"","city"=>"Irupi","state"=>"","zip"=>"29398-000"),
  array("description"=>"Mita","address1"=>"978 Russell Parkway","address2"=>"Marketing","address3"=>"","city"=>"Zhonghechang","state"=>"","zip"=>""),
  array("description"=>"Photolist","address1"=>"6434 Claremont Parkway","address2"=>"Human Resources","address3"=>"04-6435096","city"=>"Shuigou’ao","state"=>"","zip"=>""),
  array("description"=>"Yotz","address1"=>"7790 Texas Road","address2"=>"Support","address3"=>"","city"=>"Ashikaga","state"=>"","zip"=>"374-0079"),
  array("description"=>"Youbridge","address1"=>"4 Ramsey Way","address2"=>"Training","address3"=>"","city"=>"Jaguarari","state"=>"","zip"=>"48960-000"),
  array("description"=>"Thoughtsphere","address1"=>"614 Dawn Avenue","address2"=>"Training","address3"=>"","city"=>"Baranti","state"=>"","zip"=>""),
  array("description"=>"Devpulse","address1"=>"187 Meadow Valley Plaza","address2"=>"","address3"=>"","city"=>"Itajubá","state"=>"","zip"=>"37500-000"),
  array("description"=>"Youbridge","address1"=>"4831 Annamark Junction","address2"=>"","address3"=>"","city"=>"Mengenkrajan","state"=>"","zip"=>""),
  array("description"=>"Realfire","address1"=>"7 Parkside Junction","address2"=>"Research and Development","address3"=>"","city"=>"Llanera","state"=>"","zip"=>"3126"),
  array("description"=>"Myworks","address1"=>"04891 Donald Trail","address2"=>"Accounting","address3"=>"46-5611597","city"=>"Shin’ichi","state"=>"","zip"=>"729-3111"),
  array("description"=>"Gabtune","address1"=>"2317 Larry Road","address2"=>"Services","address3"=>"","city"=>"Puerto Varas","state"=>"","zip"=>""),
  array("description"=>"Eare","address1"=>"4173 Merry Drive","address2"=>"","address3"=>"","city"=>"Jiwei","state"=>"","zip"=>""),
  array("description"=>"Avamba","address1"=>"859 Commercial Pass","address2"=>"Engineering","address3"=>"","city"=>"Yanqian","state"=>"","zip"=>""),
  array("description"=>"Aibox","address1"=>"0 Grover Parkway","address2"=>"Training","address3"=>"","city"=>"Hule","state"=>"","zip"=>""),
  array("description"=>"Zoomzone","address1"=>"478 International Point","address2"=>"Engineering","address3"=>"","city"=>"Ciudad Barrios","state"=>"","zip"=>""),
  array("description"=>"Tagchat","address1"=>"448 Bashford Trail","address2"=>"Sales","address3"=>"","city"=>"Malitbog","state"=>"","zip"=>"8704"),
  array("description"=>"Divavu","address1"=>"7648 Mayfield Plaza","address2"=>"Human Resources","address3"=>"","city"=>"Paraíso","state"=>"","zip"=>"30201"),
  array("description"=>"Youspan","address1"=>"56947 Warbler Road","address2"=>"Training","address3"=>"","city"=>"Kaem","state"=>"","zip"=>""),
  array("description"=>"Edgewire","address1"=>"3804 Warner Hill","address2"=>"Marketing","address3"=>"","city"=>"Jintang","state"=>"","zip"=>""),
  array("description"=>"Mymm","address1"=>"00961 Paget Street","address2"=>"Engineering","address3"=>"","city"=>"Härnösand","state"=>"Västernorrland","zip"=>"871 33"),
  array("description"=>"Browseblab","address1"=>"93 Fair Oaks Circle","address2"=>"Marketing","address3"=>"","city"=>"Nsukka","state"=>"","zip"=>""),
  array("description"=>"Thoughtstorm","address1"=>"44319 Coleman Trail","address2"=>"Sales","address3"=>"","city"=>"Jieguanting","state"=>"","zip"=>""),
  array("description"=>"Gigashots","address1"=>"66180 Union Hill","address2"=>"","address3"=>"69-7619589","city"=>"Sanbao","state"=>"","zip"=>""),
  array("description"=>"Divanoodle","address1"=>"596 Melrose Avenue","address2"=>"Product Management","address3"=>"","city"=>"Сарај","state"=>"","zip"=>"1234"),
  array("description"=>"Brightbean","address1"=>"68 Grover Road","address2"=>"Legal","address3"=>"","city"=>"Sigu","state"=>"","zip"=>""),
  array("description"=>"Eayo","address1"=>"26 Pennsylvania Road","address2"=>"Product Management","address3"=>"","city"=>"Montargis","state"=>"","zip"=>"45204 CEDEX"),
  array("description"=>"Bubbletube","address1"=>"875 Welch Drive","address2"=>"Sales","address3"=>"","city"=>"Bagong Barrio","state"=>"","zip"=>"7209"),
  array("description"=>"Eayo","address1"=>"2275 Dapin Circle","address2"=>"Business Development","address3"=>"","city"=>"San Miguel de Tucumán","state"=>"","zip"=>"4137"),
  array("description"=>"Wikivu","address1"=>"76845 Old Gate Point","address2"=>"","address3"=>"","city"=>"San Cristóbal","state"=>"","zip"=>""),
  array("description"=>"Fliptune","address1"=>"34465 Sheridan Junction","address2"=>"Product Management","address3"=>"","city"=>"Berehomet","state"=>"","zip"=>""),
  array("description"=>"Shuffledrive","address1"=>"1886 Kings Parkway","address2"=>"Accounting","address3"=>"","city"=>"Gaur","state"=>"","zip"=>""),
  array("description"=>"Tazzy","address1"=>"69 Pleasure Plaza","address2"=>"Business Development","address3"=>"","city"=>"Pitumarca","state"=>"","zip"=>""),
  array("description"=>"Rhynyx","address1"=>"82295 Laurel Pass","address2"=>"Business Development","address3"=>"","city"=>"Krivyanskaya","state"=>"","zip"=>"347686"),
  array("description"=>"Fadeo","address1"=>"40 Meadow Valley Point","address2"=>"Accounting","address3"=>"","city"=>"Shikeng","state"=>"","zip"=>""),
  array("description"=>"Realbuzz","address1"=>"4911 South Crossing","address2"=>"Sales","address3"=>"52-7733274","city"=>"Pompano Beach","state"=>"Florida","zip"=>"33064"),
  array("description"=>"Aibox","address1"=>"1 Manitowish Pass","address2"=>"Services","address3"=>"","city"=>"Poxin","state"=>"","zip"=>""),
  array("description"=>"Fivebridge","address1"=>"60629 Sauthoff Circle","address2"=>"","address3"=>"","city"=>"Mambulo","state"=>"","zip"=>""),
  array("description"=>"Meeveo","address1"=>"18959 Farwell Drive","address2"=>"Legal","address3"=>"","city"=>"Nowa Sarzyna","state"=>"","zip"=>"37-310"),
  array("description"=>"Realcube","address1"=>"2 Carberry Crossing","address2"=>"Support","address3"=>"","city"=>"Deauville","state"=>"Basse-Normandie","zip"=>"14804 CEDEX"),
  array("description"=>"Blogtag","address1"=>"5 Homewood Plaza","address2"=>"Support","address3"=>"","city"=>"Petrolina","state"=>"","zip"=>"56300-000"),
  array("description"=>"Skiptube","address1"=>"1 High Crossing Place","address2"=>"","address3"=>"","city"=>"Ottawa","state"=>"","zip"=>"J8Y"),
  array("description"=>"Blogtags","address1"=>"944 Carberry Trail","address2"=>"Legal","address3"=>"","city"=>"Jatisari","state"=>"","zip"=>""),
  array("description"=>"Chatterbridge","address1"=>"4 Thierer Drive","address2"=>"Support","address3"=>"","city"=>"Strančice","state"=>"","zip"=>"251 63"),
  array("description"=>"Zoomdog","address1"=>"08480 Holy Cross Trail","address2"=>"","address3"=>"","city"=>"Acarigua","state"=>"","zip"=>""),
  array("description"=>"Mymm","address1"=>"9 Drewry Center","address2"=>"Legal","address3"=>"","city"=>"Urazovka","state"=>"","zip"=>"607497"),
  array("description"=>"Flashdog","address1"=>"2510 Rutledge Terrace","address2"=>"Product Management","address3"=>"84-4153857","city"=>"Cachoeiras de Macacu","state"=>"","zip"=>"28680-000"),
  array("description"=>"Oyope","address1"=>"480 Londonderry Road","address2"=>"Engineering","address3"=>"","city"=>"Chunhu","state"=>"","zip"=>""),
  array("description"=>"Yodel","address1"=>"72 Troy Way","address2"=>"Support","address3"=>"95-7101361","city"=>"Madīnat ash Shamāl","state"=>"","zip"=>""),
  array("description"=>"Roodel","address1"=>"4 Oakridge Alley","address2"=>"Research and Development","address3"=>"","city"=>"Linköping","state"=>"Östergötland","zip"=>"582 46"),
  array("description"=>"Janyx","address1"=>"78 Knutson Road","address2"=>"Services","address3"=>"","city"=>"Yongshan","state"=>"","zip"=>""),
  array("description"=>"Tagtune","address1"=>"21498 Prentice Drive","address2"=>"Training","address3"=>"81-9148286","city"=>"Parreira","state"=>"Santarém","zip"=>"2140-514"),
  array("description"=>"Rhybox","address1"=>"0137 Sheridan Lane","address2"=>"Marketing","address3"=>"","city"=>"Quesada","state"=>"","zip"=>"21001"),
  array("description"=>"Ailane","address1"=>"20 Muir Crossing","address2"=>"Marketing","address3"=>"27-7180000","city"=>"Sorol","state"=>"","zip"=>""),
  array("description"=>"Myworks","address1"=>"75 Darwin Center","address2"=>"Human Resources","address3"=>"","city"=>"Atabayan","state"=>"","zip"=>"5021"),
  array("description"=>"Skyndu","address1"=>"3 Ludington Road","address2"=>"","address3"=>"","city"=>"Lanas","state"=>"","zip"=>"1200"),
  array("description"=>"Buzzbean","address1"=>"56 Algoma Circle","address2"=>"Sales","address3"=>"","city"=>"Xibu","state"=>"","zip"=>""),
  array("description"=>"Photobug","address1"=>"54 Erie Way","address2"=>"","address3"=>"","city"=>"Dakingari","state"=>"","zip"=>""),
  array("description"=>"Kwimbee","address1"=>"6908 Nelson Hill","address2"=>"","address3"=>"11-2354181","city"=>"Colorado Springs","state"=>"Colorado","zip"=>"80935"),
  array("description"=>"Realcube","address1"=>"12 Reindahl Pass","address2"=>"Services","address3"=>"","city"=>"Pagak","state"=>"","zip"=>""),
  array("description"=>"Fatz","address1"=>"8 Fremont Street","address2"=>"Business Development","address3"=>"","city"=>"Dame-Marie","state"=>"","zip"=>""),
  array("description"=>"Lazz","address1"=>"457 Schlimgen Junction","address2"=>"","address3"=>"","city"=>"Ngã Bảy","state"=>"","zip"=>""),
  array("description"=>"Feedbug","address1"=>"9 Ilene Lane","address2"=>"Legal","address3"=>"","city"=>"Torslanda","state"=>"Västra Götaland","zip"=>"423 43"),
  array("description"=>"Brainlounge","address1"=>"5 Arizona Way","address2"=>"Training","address3"=>"","city"=>"Miejsce Piastowe","state"=>"","zip"=>"38-430"),
  array("description"=>"Katz","address1"=>"15 Debra Point","address2"=>"Training","address3"=>"","city"=>"Daqiao","state"=>"","zip"=>""),
  array("description"=>"Jabbersphere","address1"=>"9579 Hallows Plaza","address2"=>"","address3"=>"79-2289236","city"=>"Połomia","state"=>"","zip"=>"44-323"),
  array("description"=>"Gigazoom","address1"=>"4 Butternut Point","address2"=>"","address3"=>"","city"=>"Kosów Lacki","state"=>"","zip"=>"08-330"),
  array("description"=>"Pixoboo","address1"=>"6 Michigan Junction","address2"=>"","address3"=>"","city"=>"Linao","state"=>"","zip"=>"2017"),
  array("description"=>"Zooveo","address1"=>"07764 Pleasure Court","address2"=>"Research and Development","address3"=>"","city"=>"Herzliya Pituah","state"=>"","zip"=>""),
  array("description"=>"Pixoboo","address1"=>"68 Bunting Avenue","address2"=>"Marketing","address3"=>"","city"=>"Boevange-sur-Attert","state"=>"","zip"=>"L-8711"),
  array("description"=>"Jayo","address1"=>"4514 Almo Lane","address2"=>"","address3"=>"","city"=>"Pagelaran","state"=>"","zip"=>""),
  array("description"=>"Mudo","address1"=>"21454 Golf Course Road","address2"=>"","address3"=>"","city"=>"Garmo","state"=>"","zip"=>""),
  array("description"=>"Voonyx","address1"=>"0862 Cody Lane","address2"=>"Research and Development","address3"=>"","city"=>"Honolulu","state"=>"","zip"=>"96835"),
  array("description"=>"Avaveo","address1"=>"62 Fisk Street","address2"=>"","address3"=>"","city"=>"Katipunan","state"=>"","zip"=>"7109"),
  array("description"=>"Mynte","address1"=>"88006 Dahle Trail","address2"=>"Sales","address3"=>"","city"=>"Jugezhuang","state"=>"","zip"=>""),
  array("description"=>"Kimia","address1"=>"1 Arapahoe Center","address2"=>"Accounting","address3"=>"","city"=>"Tsiatsan","state"=>"","zip"=>""),
  array("description"=>"Skibox","address1"=>"4 Farragut Street","address2"=>"Engineering","address3"=>"","city"=>"Jabon","state"=>"","zip"=>""),
  array("description"=>"Flipbug","address1"=>"0 Pepper Wood Parkway","address2"=>"Research and Development","address3"=>"74-5621418","city"=>"Krasnoye","state"=>"","zip"=>"652577"),
  array("description"=>"Nlounge","address1"=>"6229 Veith Point","address2"=>"Research and Development","address3"=>"","city"=>"Dikirnis","state"=>"","zip"=>""),
  array("description"=>"Layo","address1"=>"70122 Homewood Trail","address2"=>"","address3"=>"","city"=>"Sanshilipu","state"=>"","zip"=>""),
  array("description"=>"Quinu","address1"=>"948 Dennis Crossing","address2"=>"Research and Development","address3"=>"","city"=>"Abū Ghaush","state"=>"","zip"=>""),
  array("description"=>"Yotz","address1"=>"33 Menomonie Street","address2"=>"Legal","address3"=>"","city"=>"Kuvandyk","state"=>"","zip"=>"462244"),
  array("description"=>"Omba","address1"=>"48345 Moland Alley","address2"=>"Engineering","address3"=>"","city"=>"Valparaíso","state"=>"","zip"=>""),
  array("description"=>"Jetwire","address1"=>"133 Oak Valley Drive","address2"=>"Business Development","address3"=>"","city"=>"Newton","state"=>"England","zip"=>"NG34"),
  array("description"=>"Quatz","address1"=>"9852 Del Mar Alley","address2"=>"Human Resources","address3"=>"","city"=>"Wangkung","state"=>"","zip"=>""),
  array("description"=>"Babblestorm","address1"=>"699 Monica Circle","address2"=>"Business Development","address3"=>"","city"=>"Concepción","state"=>"","zip"=>""),
  array("description"=>"Skinte","address1"=>"8 Southridge Park","address2"=>"Product Management","address3"=>"51-5556327","city"=>"Apaga","state"=>"","zip"=>""),
  array("description"=>"Roodel","address1"=>"95090 Portage Plaza","address2"=>"Marketing","address3"=>"11-4133874","city"=>"Darfield","state"=>"","zip"=>"7541"),
  array("description"=>"Wikizz","address1"=>"45345 Sunnyside Avenue","address2"=>"Product Management","address3"=>"","city"=>"Garajati","state"=>"","zip"=>""),
  array("description"=>"Trilia","address1"=>"9658 Algoma Parkway","address2"=>"","address3"=>"","city"=>"Kufa","state"=>"","zip"=>""),
  array("description"=>"Quire","address1"=>"01 Ryan Park","address2"=>"Support","address3"=>"","city"=>"Toulouse","state"=>"Midi-Pyrénées","zip"=>"31201 CEDEX 2"),
  array("description"=>"Rhyzio","address1"=>"44768 Crowley Avenue","address2"=>"Training","address3"=>"","city"=>"Quảng Yên","state"=>"","zip"=>""),
  array("description"=>"Riffwire","address1"=>"4 Maple Park","address2"=>"Engineering","address3"=>"","city"=>"Emiliano Zapata","state"=>"Oaxaca","zip"=>"70805"),
  array("description"=>"Voolia","address1"=>"71273 Eastwood Pass","address2"=>"Marketing","address3"=>"","city"=>"Aldeia de Juzo","state"=>"Lisboa","zip"=>"2750-015"),
  array("description"=>"Divape","address1"=>"6 Dovetail Center","address2"=>"","address3"=>"","city"=>"Altay","state"=>"","zip"=>""),
  array("description"=>"Ntags","address1"=>"622 Clarendon Way","address2"=>"","address3"=>"","city"=>"Baraguá","state"=>"","zip"=>""),
  array("description"=>"Blogpad","address1"=>"0261 Marquette Drive","address2"=>"Sales","address3"=>"","city"=>"Jianjiang","state"=>"","zip"=>""),
  array("description"=>"Skipfire","address1"=>"480 Talisman Court","address2"=>"","address3"=>"","city"=>"Hostouň","state"=>"","zip"=>"345 25"),
  array("description"=>"Ozu","address1"=>"930 Arapahoe Center","address2"=>"","address3"=>"","city"=>"San Agustin","state"=>"","zip"=>"8305"),
  array("description"=>"Zoovu","address1"=>"1 Columbus Terrace","address2"=>"","address3"=>"65-1765478","city"=>"Staroutkinsk","state"=>"","zip"=>"623036"),
  array("description"=>"Oyondu","address1"=>"03633 Dovetail Pass","address2"=>"","address3"=>"","city"=>"Midleton","state"=>"","zip"=>"P25"),
  array("description"=>"Tazzy","address1"=>"7 Charing Cross Drive","address2"=>"Product Management","address3"=>"","city"=>"Srpska Crnja","state"=>"","zip"=>""),
  array("description"=>"Thoughtsphere","address1"=>"6652 Sycamore Trail","address2"=>"Human Resources","address3"=>"","city"=>"Wangpu","state"=>"","zip"=>""),
  array("description"=>"Lazz","address1"=>"4628 Hermina Drive","address2"=>"","address3"=>"","city"=>"Cerca la Source","state"=>"","zip"=>""),
  array("description"=>"Tagopia","address1"=>"917 Fordem Plaza","address2"=>"Research and Development","address3"=>"","city"=>"Timaru","state"=>"","zip"=>"7940"),
  array("description"=>"Gabtype","address1"=>"61 Orin Court","address2"=>"Business Development","address3"=>"","city"=>"Chicacao","state"=>"","zip"=>"10013"),
  array("description"=>"Avamm","address1"=>"532 Petterle Place","address2"=>"Business Development","address3"=>"","city"=>"Parista","state"=>"","zip"=>"3122"),
  array("description"=>"Trudoo","address1"=>"0093 Jackson Road","address2"=>"Product Management","address3"=>"","city"=>"Santa María de Jesús","state"=>"","zip"=>"03011"),
  array("description"=>"Buzzshare","address1"=>"33571 Susan Center","address2"=>"Accounting","address3"=>"","city"=>"Oxelösund","state"=>"Södermanland","zip"=>"613 38"),
  array("description"=>"Fiveclub","address1"=>"14 Trailsway Alley","address2"=>"Research and Development","address3"=>"","city"=>"Marolambo","state"=>"","zip"=>""),
  array("description"=>"Wikizz","address1"=>"85974 Summer Ridge Drive","address2"=>"Business Development","address3"=>"","city"=>"Pasir Mas","state"=>"Kelantan","zip"=>"17020"),
  array("description"=>"Devpoint","address1"=>"560 Mandrake Place","address2"=>"","address3"=>"02-9731958","city"=>"Fengshan","state"=>"","zip"=>""),
  array("description"=>"Kanoodle","address1"=>"165 Lake View Place","address2"=>"","address3"=>"","city"=>"Byczyna","state"=>"","zip"=>"46-220"),
  array("description"=>"Yambee","address1"=>"862 Forest Hill","address2"=>"Research and Development","address3"=>"","city"=>"Banjar Dauhpangkung","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"71728 Anhalt Avenue","address2"=>"Sales","address3"=>"86-2636972","city"=>"Cilongkrangpusaka","state"=>"","zip"=>""),
  array("description"=>"Wordify","address1"=>"9820 Arapahoe Hill","address2"=>"Accounting","address3"=>"","city"=>"Shuanghe","state"=>"","zip"=>""),
  array("description"=>"Eamia","address1"=>"689 Troy Alley","address2"=>"Support","address3"=>"","city"=>"Breda","state"=>"Provincie Noord-Brabant","zip"=>"4829"),
  array("description"=>"Skibox","address1"=>"570 Arizona Terrace","address2"=>"Services","address3"=>"","city"=>"Lins","state"=>"","zip"=>""),
  array("description"=>"Leenti","address1"=>"562 Clyde Gallagher Crossing","address2"=>"","address3"=>"","city"=>"Kedungbacin","state"=>"","zip"=>""),
  array("description"=>"Janyx","address1"=>"32592 2nd Drive","address2"=>"Product Management","address3"=>"","city"=>"Lokea","state"=>"","zip"=>""),
  array("description"=>"Dablist","address1"=>"212 Dakota Trail","address2"=>"","address3"=>"","city"=>"Badar","state"=>"","zip"=>"665212"),
  array("description"=>"Abata","address1"=>"3168 Independence Plaza","address2"=>"","address3"=>"","city"=>"Rodnikovskaya","state"=>"","zip"=>"357565"),
  array("description"=>"Tazz","address1"=>"57668 Dwight Parkway","address2"=>"Engineering","address3"=>"","city"=>"Yeşilköy","state"=>"Samsun","zip"=>"55530"),
  array("description"=>"Oyope","address1"=>"03 Maple Wood Drive","address2"=>"Product Management","address3"=>"","city"=>"Asnières-sur-Seine","state"=>"Île-de-France","zip"=>"92665 CEDEX"),
  array("description"=>"Skivee","address1"=>"882 Marcy Trail","address2"=>"Research and Development","address3"=>"","city"=>"Salon-de-Provence","state"=>"Provence-Alpes-Côte d'Azur","zip"=>"13662 CEDEX"),
  array("description"=>"Quatz","address1"=>"60384 Melby Terrace","address2"=>"Accounting","address3"=>"","city"=>"San Sebastian","state"=>"","zip"=>"29950"),
  array("description"=>"Jaxworks","address1"=>"3820 Di Loreto Trail","address2"=>"","address3"=>"","city"=>"Melaka","state"=>"Melaka","zip"=>"75910"),
  array("description"=>"Babbleopia","address1"=>"56880 Eliot Center","address2"=>"Training","address3"=>"","city"=>"Chegutu","state"=>"","zip"=>""),
  array("description"=>"Fatz","address1"=>"1 Blackbird Alley","address2"=>"Product Management","address3"=>"","city"=>"‘Afrīn","state"=>"","zip"=>""),
  array("description"=>"Bubblemix","address1"=>"7 Morningstar Park","address2"=>"Services","address3"=>"","city"=>"Xiexiong","state"=>"","zip"=>""),
  array("description"=>"Zoozzy","address1"=>"7 Heffernan Circle","address2"=>"Legal","address3"=>"","city"=>"Liski","state"=>"","zip"=>"397920"),
  array("description"=>"Mynte","address1"=>"0 Menomonie Alley","address2"=>"Legal","address3"=>"","city"=>"Digne-les-Bains","state"=>"Provence-Alpes-Côte d'Azur","zip"=>"04004 CEDEX"),
  array("description"=>"Vitz","address1"=>"896 Huxley Drive","address2"=>"","address3"=>"","city"=>"Karanganyar","state"=>"","zip"=>""),
  array("description"=>"Centimia","address1"=>"90656 Shoshone Lane","address2"=>"","address3"=>"32-7330050","city"=>"Puerto Rico","state"=>"","zip"=>""),
  array("description"=>"Browsezoom","address1"=>"101 Sycamore Parkway","address2"=>"","address3"=>"","city"=>"Xiangride","state"=>"","zip"=>""),
  array("description"=>"Photospace","address1"=>"06916 Ludington Place","address2"=>"Services","address3"=>"","city"=>"Ilembula","state"=>"","zip"=>""),
  array("description"=>"Jabbersphere","address1"=>"81274 Schurz Pass","address2"=>"Product Management","address3"=>"","city"=>"Buzet","state"=>"","zip"=>"52420"),
  array("description"=>"Quire","address1"=>"1 Eggendart Park","address2"=>"Support","address3"=>"","city"=>"Pŭrvomaytsi","state"=>"","zip"=>"5139"),
  array("description"=>"Wikizz","address1"=>"3090 Mesta Road","address2"=>"Research and Development","address3"=>"","city"=>"Hezhai","state"=>"","zip"=>""),
  array("description"=>"Trilia","address1"=>"070 Union Avenue","address2"=>"Product Management","address3"=>"43-5732028","city"=>"Mungkin","state"=>"","zip"=>""),
  array("description"=>"Aimbo","address1"=>"50 7th Road","address2"=>"Legal","address3"=>"","city"=>"Los Pinos","state"=>"Guanajuato","zip"=>"36780"),
  array("description"=>"Edgeblab","address1"=>"18466 Lakeland Place","address2"=>"Product Management","address3"=>"","city"=>"Neochórion","state"=>"","zip"=>""),
  array("description"=>"Brightdog","address1"=>"29751 Schiller Plaza","address2"=>"Accounting","address3"=>"","city"=>"Labytnangi","state"=>"","zip"=>"629405"),
  array("description"=>"Viva","address1"=>"0166 Browning Court","address2"=>"Marketing","address3"=>"87-2036765","city"=>"Waeng Yai","state"=>"","zip"=>""),
  array("description"=>"Gigaclub","address1"=>"6245 Petterle Point","address2"=>"Services","address3"=>"","city"=>"Prokhorovka","state"=>"","zip"=>"309000"),
  array("description"=>"Pixonyx","address1"=>"670 Sunfield Hill","address2"=>"Training","address3"=>"","city"=>"Bolembre","state"=>"Lisboa","zip"=>""),
  array("description"=>"Fivebridge","address1"=>"6225 Surrey Street","address2"=>"Marketing","address3"=>"","city"=>"Kota Kinabalu","state"=>"Sabah","zip"=>"88906"),
  array("description"=>"Devcast","address1"=>"33760 Valley Edge Road","address2"=>"Research and Development","address3"=>"","city"=>"Lewolen","state"=>"","zip"=>""),
  array("description"=>"Dabshots","address1"=>"745 Dryden Park","address2"=>"Services","address3"=>"","city"=>"Broniszewice","state"=>"","zip"=>"63-304"),
  array("description"=>"Wordtune","address1"=>"6271 Fieldstone Alley","address2"=>"Product Management","address3"=>"94-1160544","city"=>"Phoenix","state"=>"Arizona","zip"=>"85010"),
  array("description"=>"Eidel","address1"=>"39 Sugar Parkway","address2"=>"Services","address3"=>"","city"=>"Křížová","state"=>"","zip"=>"794 01"),
  array("description"=>"Yodo","address1"=>"56 Manitowish Road","address2"=>"","address3"=>"","city"=>"Waso","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"91 Messerschmidt Circle","address2"=>"Services","address3"=>"","city"=>"Bolobo","state"=>"","zip"=>""),
  array("description"=>"Devshare","address1"=>"6678 Bay Parkway","address2"=>"Marketing","address3"=>"","city"=>"Tulsīpur","state"=>"","zip"=>""),
  array("description"=>"Twitterbridge","address1"=>"673 Fordem Point","address2"=>"Services","address3"=>"","city"=>"Twyford","state"=>"England","zip"=>"LE14"),
  array("description"=>"Dynabox","address1"=>"1862 Dayton Point","address2"=>"Marketing","address3"=>"36-9460627","city"=>"Sanshan","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"799 Anthes Plaza","address2"=>"Product Management","address3"=>"","city"=>"Dongchuan","state"=>"","zip"=>""),
  array("description"=>"Mynte","address1"=>"74186 Rieder Trail","address2"=>"Legal","address3"=>"","city"=>"Baolong","state"=>"","zip"=>""),
  array("description"=>"Gabvine","address1"=>"6471 Union Plaza","address2"=>"Human Resources","address3"=>"","city"=>"Timon","state"=>"","zip"=>""),
  array("description"=>"Skippad","address1"=>"921 Packers Terrace","address2"=>"Training","address3"=>"","city"=>"Wengaingo","state"=>"","zip"=>""),
  array("description"=>"Zoomlounge","address1"=>"54 Blue Bill Park Junction","address2"=>"Engineering","address3"=>"","city"=>"Ząbkowice Śląskie","state"=>"","zip"=>"57-201"),
  array("description"=>"Aibox","address1"=>"5415 Lerdahl Place","address2"=>"Engineering","address3"=>"","city"=>"Fenghuanglu","state"=>"","zip"=>""),
  array("description"=>"Kwideo","address1"=>"758 Dovetail Center","address2"=>"","address3"=>"","city"=>"Kishi","state"=>"","zip"=>""),
  array("description"=>"Browsetype","address1"=>"95084 Karstens Center","address2"=>"Product Management","address3"=>"","city"=>"Pondokwungu","state"=>"","zip"=>""),
  array("description"=>"Snaptags","address1"=>"039 Briar Crest Court","address2"=>"Support","address3"=>"","city"=>"Sarov","state"=>"","zip"=>"607189"),
  array("description"=>"Janyx","address1"=>"97 Logan Pass","address2"=>"Engineering","address3"=>"","city"=>"Pervoavgustovskiy","state"=>"","zip"=>"307513"),
  array("description"=>"Layo","address1"=>"2 Anniversary Court","address2"=>"Training","address3"=>"","city"=>"Yong’an","state"=>"","zip"=>""),
  array("description"=>"Twitterbeat","address1"=>"77 Anzinger Center","address2"=>"","address3"=>"","city"=>"Santiago","state"=>"","zip"=>""),
  array("description"=>"Topiclounge","address1"=>"74368 Ridgeview Lane","address2"=>"Accounting","address3"=>"","city"=>"Sumberdangdang","state"=>"","zip"=>""),
  array("description"=>"Jabbercube","address1"=>"443 Acker Hill","address2"=>"","address3"=>"55-6599640","city"=>"Lanpelan","state"=>"","zip"=>""),
  array("description"=>"Tagcat","address1"=>"63 Sachtjen Circle","address2"=>"","address3"=>"","city"=>"Tuchola","state"=>"","zip"=>"89-501"),
  array("description"=>"Gabtune","address1"=>"281 Banding Place","address2"=>"Product Management","address3"=>"39-8183025","city"=>"Kutacane","state"=>"","zip"=>""),
  array("description"=>"Twitterworks","address1"=>"924 Rieder Place","address2"=>"Research and Development","address3"=>"","city"=>"Lampa","state"=>"","zip"=>""),
  array("description"=>"Devify","address1"=>"04854 Saint Paul Court","address2"=>"Research and Development","address3"=>"","city"=>"Tiên Phước","state"=>"","zip"=>""),
  array("description"=>"Roombo","address1"=>"64399 Oak Valley Circle","address2"=>"","address3"=>"","city"=>"Cosquín","state"=>"","zip"=>""),
  array("description"=>"Lazz","address1"=>"49797 Huxley Lane","address2"=>"Services","address3"=>"","city"=>"Xintang","state"=>"","zip"=>""),
  array("description"=>"Blognation","address1"=>"408 Jana Drive","address2"=>"Services","address3"=>"","city"=>"Citasuk","state"=>"","zip"=>""),
  array("description"=>"Voonyx","address1"=>"6458 Carberry Way","address2"=>"Research and Development","address3"=>"","city"=>"Pathein","state"=>"","zip"=>""),
  array("description"=>"Flashset","address1"=>"0 Vidon Trail","address2"=>"Sales","address3"=>"","city"=>"Az Ziyārah","state"=>"","zip"=>""),
  array("description"=>"Gabtype","address1"=>"877 Derek Terrace","address2"=>"Product Management","address3"=>"","city"=>"Ningdun","state"=>"","zip"=>""),
  array("description"=>"Youspan","address1"=>"576 Kingsford Center","address2"=>"Sales","address3"=>"","city"=>"Banjar Bucu","state"=>"","zip"=>""),
  array("description"=>"Rhynoodle","address1"=>"68167 Longview Road","address2"=>"","address3"=>"","city"=>"Blažovice","state"=>"","zip"=>"664 08"),
  array("description"=>"Zoombeat","address1"=>"2 Schmedeman Crossing","address2"=>"Accounting","address3"=>"","city"=>"Kumai","state"=>"","zip"=>""),
  array("description"=>"Rhybox","address1"=>"13904 Iowa Circle","address2"=>"","address3"=>"","city"=>"Gritsovskiy","state"=>"","zip"=>""),
  array("description"=>"Gigabox","address1"=>"9468 Fairview Terrace","address2"=>"Support","address3"=>"","city"=>"Évreux","state"=>"Haute-Normandie","zip"=>"27036 CEDEX"),
  array("description"=>"Tagchat","address1"=>"224 Johnson Parkway","address2"=>"","address3"=>"","city"=>"Xuedian","state"=>"","zip"=>""),
  array("description"=>"Jetwire","address1"=>"7 Westend Court","address2"=>"Human Resources","address3"=>"","city"=>"Bagadó","state"=>"","zip"=>"271058"),
  array("description"=>"Mymm","address1"=>"570 Portage Road","address2"=>"Marketing","address3"=>"","city"=>"Armstrong","state"=>"British Columbia","zip"=>"M9R"),
  array("description"=>"Eadel","address1"=>"313 Hoepker Court","address2"=>"","address3"=>"","city"=>"Anxi","state"=>"","zip"=>""),
  array("description"=>"Meevee","address1"=>"82523 Arapahoe Way","address2"=>"","address3"=>"51-3855099","city"=>"Kibingo","state"=>"","zip"=>""),
  array("description"=>"Skajo","address1"=>"3837 Northview Pass","address2"=>"Engineering","address3"=>"","city"=>"Korçë","state"=>"","zip"=>""),
  array("description"=>"Dabshots","address1"=>"368 Lyons Street","address2"=>"Support","address3"=>"","city"=>"Lombo Meão","state"=>"Aveiro","zip"=>"3840-467"),
  array("description"=>"Skyba","address1"=>"36276 Nova Center","address2"=>"Sales","address3"=>"","city"=>"Ad Dimnah","state"=>"","zip"=>""),
  array("description"=>"Jetpulse","address1"=>"80409 Messerschmidt Road","address2"=>"Marketing","address3"=>"06-9221925","city"=>"Igaraçu do Tietê","state"=>"","zip"=>""),
  array("description"=>"Eare","address1"=>"30 Dorton Way","address2"=>"Research and Development","address3"=>"","city"=>"Đắk Mâm","state"=>"","zip"=>""),
  array("description"=>"Jabberstorm","address1"=>"59224 Weeping Birch Drive","address2"=>"Research and Development","address3"=>"21-7859936","city"=>"Niška Banja","state"=>"","zip"=>""),
  array("description"=>"Katz","address1"=>"6 Esker Point","address2"=>"","address3"=>"26-8415712","city"=>"Panan","state"=>"","zip"=>"1105"),
  array("description"=>"Oyonder","address1"=>"0 Goodland Hill","address2"=>"Business Development","address3"=>"","city"=>"Tilcara","state"=>"","zip"=>"4624"),
  array("description"=>"Mynte","address1"=>"3 David Crossing","address2"=>"Training","address3"=>"","city"=>"Marseille","state"=>"Provence-Alpes-Côte d'Azur","zip"=>"13232 CEDEX 01"),
  array("description"=>"Twimm","address1"=>"38 Messerschmidt Lane","address2"=>"","address3"=>"","city"=>"Piripiri","state"=>"","zip"=>"64260-000"),
  array("description"=>"Cogidoo","address1"=>"0221 Westridge Point","address2"=>"Services","address3"=>"","city"=>"Buenavista","state"=>"","zip"=>""),
  array("description"=>"Viva","address1"=>"48880 Jenna Terrace","address2"=>"Accounting","address3"=>"","city"=>"Alor Setar","state"=>"Kedah","zip"=>"05516"),
  array("description"=>"Skyvu","address1"=>"728 Bayside Junction","address2"=>"Legal","address3"=>"","city"=>"Baoquanshan","state"=>"","zip"=>""),
  array("description"=>"Skiptube","address1"=>"16991 Mesta Avenue","address2"=>"Human Resources","address3"=>"","city"=>"Pataruman","state"=>"","zip"=>""),
  array("description"=>"Jabbersphere","address1"=>"940 Schiller Street","address2"=>"","address3"=>"","city"=>"Qingxi","state"=>"","zip"=>""),
  array("description"=>"Mybuzz","address1"=>"98 Mifflin Drive","address2"=>"Legal","address3"=>"","city"=>"Piteå","state"=>"Norrbotten","zip"=>"941 28"),
  array("description"=>"Skibox","address1"=>"9021 Welch Hill","address2"=>"Human Resources","address3"=>"","city"=>"Santa","state"=>"","zip"=>""),
  array("description"=>"Digitube","address1"=>"92 Talisman Junction","address2"=>"Research and Development","address3"=>"21-4569933","city"=>"Sundsvall","state"=>"","zip"=>"851 88"),
  array("description"=>"Wordtune","address1"=>"572 North Park","address2"=>"Human Resources","address3"=>"","city"=>"Itacarambi","state"=>"","zip"=>"39470-000"),
  array("description"=>"Jayo","address1"=>"2 Loeprich Plaza","address2"=>"Accounting","address3"=>"","city"=>"Novomoskovs’k","state"=>"","zip"=>""),
  array("description"=>"Tagopia","address1"=>"3 Melody Junction","address2"=>"Engineering","address3"=>"","city"=>"Meybod","state"=>"","zip"=>""),
  array("description"=>"Jaxworks","address1"=>"855 Oriole Plaza","address2"=>"","address3"=>"","city"=>"Samut Songkhram","state"=>"","zip"=>"75110"),
  array("description"=>"Photolist","address1"=>"3193 Burrows Trail","address2"=>"Product Management","address3"=>"","city"=>"Karavan","state"=>"","zip"=>""),
  array("description"=>"Youtags","address1"=>"6585 Morningstar Pass","address2"=>"Research and Development","address3"=>"","city"=>"Wawer","state"=>"","zip"=>"37-750"),
  array("description"=>"Flashpoint","address1"=>"88719 Lillian Park","address2"=>"Training","address3"=>"23-8556268","city"=>"Linköping","state"=>"Östergötland","zip"=>"582 46"),
  array("description"=>"Divanoodle","address1"=>"59491 Mayer Lane","address2"=>"","address3"=>"","city"=>"Mohale’s Hoek","state"=>"","zip"=>""),
  array("description"=>"Topicstorm","address1"=>"22131 Blackbird Terrace","address2"=>"","address3"=>"","city"=>"Stavropol’","state"=>"","zip"=>"356235"),
  array("description"=>"Kwimbee","address1"=>"9 Farmco Road","address2"=>"Accounting","address3"=>"","city"=>"Dawei","state"=>"","zip"=>""),
  array("description"=>"Ooba","address1"=>"45217 Anzinger Street","address2"=>"Training","address3"=>"60-5258943","city"=>"Az Zaytūnīyah","state"=>"","zip"=>""),
  array("description"=>"Avaveo","address1"=>"741 Merry Place","address2"=>"","address3"=>"61-0089796","city"=>"Buenos Aires","state"=>"","zip"=>"191017"),
  array("description"=>"Brainlounge","address1"=>"600 Canary Court","address2"=>"Legal","address3"=>"35-9026619","city"=>"Barbacena","state"=>"","zip"=>"36200-000"),
  array("description"=>"Innojam","address1"=>"370 Laurel Plaza","address2"=>"Research and Development","address3"=>"","city"=>"Néa Tríglia","state"=>"","zip"=>""),
  array("description"=>"Plajo","address1"=>"20 Spohn Plaza","address2"=>"Legal","address3"=>"","city"=>"Montpellier","state"=>"Languedoc-Roussillon","zip"=>"34038 CEDEX 1"),
  array("description"=>"Gigazoom","address1"=>"271 Elmside Alley","address2"=>"Product Management","address3"=>"","city"=>"Adir","state"=>"","zip"=>""),
  array("description"=>"Oloo","address1"=>"84388 Tennyson Drive","address2"=>"","address3"=>"","city"=>"Huazhai","state"=>"","zip"=>""),
  array("description"=>"Realpoint","address1"=>"57 Barby Drive","address2"=>"","address3"=>"43-7291086","city"=>"Nova Iguaçu","state"=>"","zip"=>"26000-000"),
  array("description"=>"Yombu","address1"=>"830 Melvin Court","address2"=>"Product Management","address3"=>"","city"=>"Jiangkou","state"=>"","zip"=>""),
  array("description"=>"Photobean","address1"=>"6420 Muir Parkway","address2"=>"Human Resources","address3"=>"","city"=>"Hägersten","state"=>"Stockholm","zip"=>"126 31"),
  array("description"=>"Ainyx","address1"=>"4 Forest Run Trail","address2"=>"","address3"=>"","city"=>"Kitango","state"=>"","zip"=>"6407"),
  array("description"=>"Quinu","address1"=>"680 Summerview Park","address2"=>"Training","address3"=>"","city"=>"Barbudo","state"=>"Braga","zip"=>"4730-068"),
  array("description"=>"Snaptags","address1"=>"65 Springview Hill","address2"=>"","address3"=>"","city"=>"Pindamonhangaba","state"=>"","zip"=>"12400-000"),
  array("description"=>"Topdrive","address1"=>"90877 Summit Plaza","address2"=>"","address3"=>"","city"=>"La Tebaida","state"=>"","zip"=>"633027"),
  array("description"=>"Mynte","address1"=>"6027 Menomonie Street","address2"=>"","address3"=>"64-1825630","city"=>"Gununggoong","state"=>"","zip"=>""),
  array("description"=>"Yacero","address1"=>"6 Service Center","address2"=>"","address3"=>"","city"=>"Lille","state"=>"Nord-Pas-de-Calais","zip"=>"59895 CEDEX 9"),
  array("description"=>"Topiclounge","address1"=>"175 La Follette Lane","address2"=>"","address3"=>"","city"=>"Pécs","state"=>"Baranya","zip"=>"7631"),
  array("description"=>"Zoombox","address1"=>"70641 Hauk Alley","address2"=>"","address3"=>"","city"=>"Hafrsfjord","state"=>"Rogaland","zip"=>"4089"),
  array("description"=>"JumpXS","address1"=>"696 Chive Park","address2"=>"","address3"=>"","city"=>"München","state"=>"Bayern","zip"=>"80686"),
  array("description"=>"Demimbu","address1"=>"98 Lunder Hill","address2"=>"","address3"=>"","city"=>"Kaliska","state"=>"","zip"=>"83-260"),
  array("description"=>"Kazio","address1"=>"79 Randy Parkway","address2"=>"Marketing","address3"=>"","city"=>"Krzeszów","state"=>"","zip"=>""),
  array("description"=>"Twinte","address1"=>"5 Green Ridge Parkway","address2"=>"Training","address3"=>"","city"=>"Paterson","state"=>"New Jersey","zip"=>"07522"),
  array("description"=>"Shuffletag","address1"=>"529 Myrtle Place","address2"=>"Support","address3"=>"","city"=>"Same","state"=>"","zip"=>""),
  array("description"=>"Yamia","address1"=>"06555 Surrey Circle","address2"=>"Services","address3"=>"","city"=>"Trmice","state"=>"","zip"=>"400 04"),
  array("description"=>"Ailane","address1"=>"24 Loomis Avenue","address2"=>"Support","address3"=>"","city"=>"Dar es Salaam","state"=>"","zip"=>""),
  array("description"=>"Shufflester","address1"=>"0 Schmedeman Way","address2"=>"","address3"=>"","city"=>"El Ángel","state"=>"","zip"=>""),
  array("description"=>"Tavu","address1"=>"19433 Carberry Road","address2"=>"Support","address3"=>"","city"=>"Sanjian","state"=>"","zip"=>""),
  array("description"=>"Skivee","address1"=>"8 Rusk Hill","address2"=>"","address3"=>"","city"=>"Jingzhou","state"=>"","zip"=>""),
  array("description"=>"Rhynoodle","address1"=>"4899 Ridgeview Junction","address2"=>"Business Development","address3"=>"","city"=>"Sariwŏn","state"=>"","zip"=>""),
  array("description"=>"Riffwire","address1"=>"11874 Fairview Park","address2"=>"","address3"=>"","city"=>"5 de Mayo","state"=>"Veracruz Llave","zip"=>"93350"),
  array("description"=>"Wikibox","address1"=>"02 Esker Road","address2"=>"Accounting","address3"=>"","city"=>"Montgomery","state"=>"Alabama","zip"=>"36104"),
  array("description"=>"Jabberbean","address1"=>"0410 Prairie Rose Point","address2"=>"","address3"=>"","city"=>"Rossosh’","state"=>"","zip"=>"689400"),
  array("description"=>"Topicblab","address1"=>"7401 Oriole Lane","address2"=>"Support","address3"=>"","city"=>"Garajati","state"=>"","zip"=>""),
  array("description"=>"Trunyx","address1"=>"108 Sloan Crossing","address2"=>"Services","address3"=>"62-3125484","city"=>"Huangqi","state"=>"","zip"=>""),
  array("description"=>"Talane","address1"=>"6 Village Road","address2"=>"","address3"=>"","city"=>"Kumanis","state"=>"","zip"=>""),
  array("description"=>"Mydeo","address1"=>"76 Prairie Rose Parkway","address2"=>"Business Development","address3"=>"","city"=>"Paris 15","state"=>"Île-de-France","zip"=>"75902 CEDEX 15"),
  array("description"=>"Oyonder","address1"=>"9 Rowland Hill","address2"=>"Legal","address3"=>"","city"=>"Panunggangan","state"=>"","zip"=>""),
  array("description"=>"Flashset","address1"=>"392 Katie Avenue","address2"=>"Marketing","address3"=>"","city"=>"Kurgan","state"=>"","zip"=>""),
  array("description"=>"Vimbo","address1"=>"26384 Maple Wood Alley","address2"=>"","address3"=>"","city"=>"Chenggan","state"=>"","zip"=>""),
  array("description"=>"Flashspan","address1"=>"2 Mayfield Plaza","address2"=>"Accounting","address3"=>"18-8336234","city"=>"Tafraout","state"=>"","zip"=>""),
  array("description"=>"Vidoo","address1"=>"26384 Ramsey Way","address2"=>"Marketing","address3"=>"94-5878580","city"=>"Morelos","state"=>"Morelos","zip"=>"62577"),
  array("description"=>"Talane","address1"=>"5 Carpenter Plaza","address2"=>"","address3"=>"","city"=>"Villamontes","state"=>"","zip"=>""),
  array("description"=>"Abata","address1"=>"94 Carpenter Alley","address2"=>"","address3"=>"","city"=>"San Ramón","state"=>"","zip"=>""),
  array("description"=>"Eimbee","address1"=>"49724 Sachtjen Drive","address2"=>"Business Development","address3"=>"","city"=>"Santo André","state"=>"","zip"=>""),
  array("description"=>"Yata","address1"=>"812 Farragut Circle","address2"=>"Legal","address3"=>"","city"=>"Santander","state"=>"Cantabria","zip"=>"39080"),
  array("description"=>"Brainverse","address1"=>"21 Mcbride Lane","address2"=>"","address3"=>"","city"=>"Khueang Nai","state"=>"","zip"=>"64150"),
  array("description"=>"Yabox","address1"=>"9662 Esch Drive","address2"=>"","address3"=>"","city"=>"Ribeirão Preto","state"=>"","zip"=>"14000-000"),
  array("description"=>"Photojam","address1"=>"47045 Boyd Lane","address2"=>"","address3"=>"","city"=>"Gaobu","state"=>"","zip"=>""),
  array("description"=>"Dynava","address1"=>"2472 Hoard Hill","address2"=>"Accounting","address3"=>"","city"=>"Inhambane","state"=>"","zip"=>""),
  array("description"=>"Zoovu","address1"=>"1481 Glendale Circle","address2"=>"","address3"=>"","city"=>"Issy-les-Moulineaux","state"=>"Île-de-France","zip"=>"92787 CEDEX 9"),
  array("description"=>"Gigabox","address1"=>"92 Burning Wood Crossing","address2"=>"Engineering","address3"=>"26-4516980","city"=>"Nesebar","state"=>"","zip"=>"8217"),
  array("description"=>"Latz","address1"=>"7315 Weeping Birch Crossing","address2"=>"Product Management","address3"=>"","city"=>"Voloshka","state"=>"","zip"=>"164051"),
  array("description"=>"Riffpedia","address1"=>"4865 New Castle Street","address2"=>"","address3"=>"49-7778163","city"=>"Merritt","state"=>"British Columbia","zip"=>"V1K"),
  array("description"=>"Zava","address1"=>"5185 Mendota Plaza","address2"=>"Business Development","address3"=>"","city"=>"Catriló","state"=>"","zip"=>"6330"),
  array("description"=>"Brainsphere","address1"=>"86 Pierstorff Terrace","address2"=>"Sales","address3"=>"","city"=>"Artjärvi","state"=>"","zip"=>"16201"),
  array("description"=>"Ntags","address1"=>"47 Clarendon Crossing","address2"=>"Marketing","address3"=>"","city"=>"Voiron","state"=>"Rhône-Alpes","zip"=>"38504 CEDEX"),
  array("description"=>"JumpXS","address1"=>"68672 Fallview Street","address2"=>"Legal","address3"=>"","city"=>"San Pedro Jocopilas","state"=>"","zip"=>"14009"),
  array("description"=>"Reallinks","address1"=>"06 Westerfield Park","address2"=>"","address3"=>"","city"=>"Igcocolo","state"=>"","zip"=>"5029"),
  array("description"=>"Tagpad","address1"=>"6893 Briar Crest Center","address2"=>"Support","address3"=>"","city"=>"Wangcao","state"=>"","zip"=>""),
  array("description"=>"Thoughtbeat","address1"=>"82029 Waxwing Plaza","address2"=>"Research and Development","address3"=>"","city"=>"Aix-en-Provence","state"=>"Provence-Alpes-Côte d'Azur","zip"=>"13617 CEDEX 1"),
  array("description"=>"Meembee","address1"=>"634 Summerview Plaza","address2"=>"Accounting","address3"=>"","city"=>"Bohorodchany","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"49 Waubesa Drive","address2"=>"","address3"=>"","city"=>"Górki","state"=>"","zip"=>"39-306"),
  array("description"=>"Youopia","address1"=>"90694 Cherokee Hill","address2"=>"Human Resources","address3"=>"","city"=>"Ipatinga","state"=>"","zip"=>"35160-000"),
  array("description"=>"Mydo","address1"=>"83594 Fordem Crossing","address2"=>"Legal","address3"=>"","city"=>"Nong Saeng","state"=>"","zip"=>"41340"),
  array("description"=>"Vinte","address1"=>"419 Stuart Junction","address2"=>"Human Resources","address3"=>"","city"=>"Paris La Défense","state"=>"Île-de-France","zip"=>"92056 CEDEX"),
  array("description"=>"Miboo","address1"=>"57664 Marcy Court","address2"=>"Support","address3"=>"","city"=>"Xianju","state"=>"","zip"=>""),
  array("description"=>"Twitternation","address1"=>"3 Corry Court","address2"=>"","address3"=>"","city"=>"Cibolek Kidul","state"=>"","zip"=>""),
  array("description"=>"Dabshots","address1"=>"66 Monica Parkway","address2"=>"Research and Development","address3"=>"","city"=>"Sochaux","state"=>"Franche-Comté","zip"=>"25609 CEDEX"),
  array("description"=>"Fatz","address1"=>"86 Muir Way","address2"=>"Support","address3"=>"","city"=>"Волочаевское","state"=>"","zip"=>"238346"),
  array("description"=>"Trupe","address1"=>"1 Commercial Street","address2"=>"","address3"=>"","city"=>"Zhoukou","state"=>"","zip"=>""),
  array("description"=>"Mynte","address1"=>"2299 Cardinal Terrace","address2"=>"Human Resources","address3"=>"","city"=>"Gizo","state"=>"","zip"=>""),
  array("description"=>"Mynte","address1"=>"3477 Anderson Court","address2"=>"","address3"=>"","city"=>"Lesuhe","state"=>"","zip"=>""),
  array("description"=>"Oyonder","address1"=>"0 Rowland Parkway","address2"=>"Marketing","address3"=>"","city"=>"Utena","state"=>"","zip"=>""),
  array("description"=>"Devbug","address1"=>"85 Farragut Center","address2"=>"Accounting","address3"=>"","city"=>"Shuiyuesi","state"=>"","zip"=>""),
  array("description"=>"Edgeblab","address1"=>"38 Valley Edge Parkway","address2"=>"Support","address3"=>"","city"=>"Yinjiang","state"=>"","zip"=>""),
  array("description"=>"Miboo","address1"=>"450 Golden Leaf Avenue","address2"=>"","address3"=>"","city"=>"Padangtepung","state"=>"","zip"=>""),
  array("description"=>"Browsebug","address1"=>"9 Gulseth Way","address2"=>"Engineering","address3"=>"","city"=>"Mora","state"=>"Dalarna","zip"=>"792 34"),
  array("description"=>"Eadel","address1"=>"65 Annamark Plaza","address2"=>"","address3"=>"","city"=>"Qinghu","state"=>"","zip"=>""),
);

// Set up doctrine objects
$emf = new EntityManagerFactory();
$em = $emf->getEntityManager();
$am = new AddressManager($em);
$cm = new CountryManager($em);
$rm = new RegionManager($em);

// Default User Credentials
$default_password = "password";
$countries = $cm->loadAll();

foreach($addresses AS $aData) {
  $address = new Address();
  $address->setDescription($aData['description'] . " - " . $aData['city'] . " - " . rand(1001,9999));
  $address->setAddress1($aData['address1']);
  $address->setAddress2($aData['address2']);
  $address->setAddress3($aData['address3']);
  $address->setCity($aData['city']);
  if($aData['state'] == null) {
    $aData['state'] = $us_states[rand(0, sizeof($us_states) - 1)]['state'];
  }
  $address->setState($aData['state']);
  if($aData['zip'] == null) {
    $aData['zip'] = rand(12345,99999);
  }
  $address->setZipcode($aData['zip']);
  $address->setCountry($countries[rand(0,sizeof($countries) - 1)]);
  $am->store($address);
}
?>
