<?php

// Populates a list of Award Types
//
// NOTE: This is a destructive operation.
// It will screw up any associated indices.
// Only run this if you're okay blowing away the entire existing database.

ini_set('display_errors', 'On');

require_once(__DIR__ . "/../config/admin/config.php");
require_once(__DIR__ . "/../config/admin/doctrine.php");
require_once(__DIR__ . "/../db/src/User.php");
require_once(__DIR__ . "/../db/UserManager.php");

// Set up doctrine objects
$emf = new EntityManagerFactory();
$em = $emf->getEntityManager();
$um = new UserManager($em);

// Default User Credentials
$default_password = "password";

// Users generated by this handy tool:
// http://listofrandomnames.com/index.cfm?textarea

$userArray = array(
  array("firstName"=>"Antoinette","lastName"=>"Agena"),
  array("firstName"=>"Garrett","lastName"=>"Gray"),
  array("firstName"=>"Darleen","lastName"=>"Deal"),
  array("firstName"=>"Willis","lastName"=>"Wafford"),
  array("firstName"=>"Rhea","lastName"=>"Rady"),
  array("firstName"=>"Elenore","lastName"=>"Edler"),
  array("firstName"=>"Verona","lastName"=>"Vidal"),
  array("firstName"=>"Kasey","lastName"=>"Kremer"),
  array("firstName"=>"Reanna","lastName"=>"Rabalais"),
  array("firstName"=>"Willene","lastName"=>"Weinman"),
  array("firstName"=>"Elane","lastName"=>"Eickhoff"),
  array("firstName"=>"Oralia","lastName"=>"Ocegueda"),
  array("firstName"=>"Rafaela","lastName"=>"Ruley"),
  array("firstName"=>"Darrin","lastName"=>"Domer"),
  array("firstName"=>"Vannessa","lastName"=>"Vogan"),
  array("firstName"=>"Nery","lastName"=>"Naylor"),
  array("firstName"=>"Edwin","lastName"=>"Emery"),
  array("firstName"=>"Yulanda","lastName"=>"Younce")
);

foreach ($userArray AS $userData) {
  $user = new User();
  $user->setFirstName($userData['firstName']);
  $user->setLastName($userData['lastName']);
  $user->setPassword($default_password);
  $user->setEmail(strtolower($userData['lastName']) . strtolower(substr($userData['firstName'], 0, 1)) . "@phoenix.jeromie.com");
  $um->store($user);
}

?>
